server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ms-sucursal

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:admin@project0.vwkot0h.mongodb.net/sucursales}
      

logging:
  level:
    root: INFO
    com.banquito.sucursal: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html